[package]
name = "word-search"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
enum-iterator = "1"
getrandom = "0.2.10"
hex = "0.4.3"
html = "0.6.2"
humantime = "2"
itertools = "0.11"
rand = "0.8"
